[build]
  command = "bundle install && bundle exec jekyll build"
  publish = "_site"

[build.environment]
  RUBY_VERSION = "3.2.2"

# (Optionnel) garder /admin accessible même en SPA/redirects
[[redirects]]
  from = "/admin"
  to = "/admin/index.html"
  status = 200
