backend:
  name: git-gateway
  branch: main

media_folder: "assets"
public_folder: "/assets"

collections:
  - name: "pages"
    label: "Pages du site"
    files:
      - file: "index.html"
        label: "Accueil"
        name: "index"
        fields:
          - {label: "Titre", name: "title", widget: "string"}
          - {label: "Contenu", name: "body", widget: "markdown"}
      - file: "about.html"
        label: "Le club"
        name: "about"
        fields:
          - {label: "Titre", name: "title", widget: "string"}
          - {label: "Contenu", name: "body", widget: "markdown"}
      - file: "agenda.html"
        label: "Agenda"
        name: "agenda"
        fields:
          - {label: "Titre", name: "title", widget: "string"}
          - {label: "Contenu", name: "body", widget: "markdown"}
      - file: "tarifs.html"
        label: "Tarifs"
        name: "tarifs"
        fields:
          - {label: "Titre", name: "title", widget: "string"}
          - {label: "Contenu", name: "body", widget: "markdown"}
      - file: "adhesion.html"
        label: "Adhésion"
        name: "adhesion"
        fields:
          - {label: "Titre", name: "title", widget: "string"}
          - {label: "Contenu", name: "body", widget: "markdown"}
      - file: "contact.html"
        label: "Contact"
        name: "contact"
        fields:
          - {label: "Titre", name: "title", widget: "string"}
          - {label: "Contenu", name: "body", widget: "markdown"}
