backend:
  name: git-gateway
  branch: main

media_folder: "assets/uploads"
public_folder: "/assets/uploads"
locale: "fr"

collections:
  - name: "pages"
    label: "Pages du site"
    label_singular: "Page"
    folder: "content"           # <- édite /content/**/*.md
    create: false               # pas de nouvelles pages depuis le CMS
    format: "frontmatter"
    extension: "md"
    nested:
      depth: 3                  # affiche l'arborescence (about/histoire, etc.)
      summary: "{{title}}"
    slug: "{{slug}}"
    fields:
      - { label: "Titre", name: "title", widget: "string" }
      - { label: "Image de couverture", name: "cover", widget: "image", required: false }
      - { label: "Contenu", name: "body", widget: "markdown" }
